version: "3.7"

volumes:
  init-db:
  data-db:
services:
  redis:
    image: redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    entrypoint: flower
    command: -A RMDP_api --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
#    volumes: [ './celery-queue:/queue' ]
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
  mongo_seed:
    image: mongo:3.2.6
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    ports:
      - '8081:8081'
#  celery:
#    build: .
#    command: celery -A RMDP_api worker -l INFO
#    environment:
#      - DEBUG=1
#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#      - CELERY_BROKER=redis://redis:6379/0
#      - CELERY_BACKEND=redis://redis:6379/0
  django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
