version: "3.7"
services:
  mongodb:
        image: mongo:latest
        container_name: mongo-server
        environment:
                 # provide your credentials here
                 - MONGO_INITDB_ROOT_USERNAME=mongoadmin
                 - MONGO_INITDB_ROOT_PASSWORD=mypass
        ports:
           - "27017:27017"
        volumes:
           # to make a persistent database surviving docker restarts
           - mongodb-volume:/data/db
           # mongodump'ed data goes here
           - ./mongo-seed-data:/data/mongo-seed-data
           # script to start the actual import (besides other custom things
           # you may want to do
           - ./mongodb-scripts:/docker-entrypoint-initdb.d
        networks:
          - mongo-compose-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    links:
        - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: mongoadmin
      ME_CONFIG_BASICAUTH_PASSWORD: mypass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypass
    ports:
      - '8081:8081'
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb
networks:
    mongo-compose-network:
      driver: bridge
volumes:
        mongodb-volume: