version: '3.1'

service:
  mongodb:
    image: mongo:4.4.4
    restart: always
    # volumes:
    #   - ./init-db:/docker-entrypoint-initdb.d
    #   - ./data-db:/data/db
    environment:
      -MONGO_INITDB_ROOT_USERNAME: root
      -MONGO_INITDB_ROOT_PASSWORD: root
      -MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      -ME_CONFIG_MONGODB_ADMINUSERNAME: root
      -ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
